In [1]:
# Importar las bibliotecas
import pandas as pd
import polars as pl

# Crear un DataFrame con Pandas
data_pandas = {
    "nombre": ["Ana", "Luis", "María", "Juan"],
    "edad": [23, 45, 34, 25],
    "ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla"]
}
df_pandas = pd.DataFrame(data_pandas)

# Operaciones básicas con Pandas
print("DataFrame con Pandas:")
print(df_pandas)
print("\nSeleccionar la columna 'nombre':")
print(df_pandas["nombre"])
print("\nFiltrar filas donde la edad es mayor de 30:")
print(df_pandas[df_pandas["edad"] > 30])

# Crear un DataFrame con Polars
df_polars = pl.DataFrame(data_pandas)

# Operaciones básicas con Polars
print("\nDataFrame con Polars:")
print(df_polars)
print("\nSeleccionar la columna 'nombre':")
print(df_polars.select("nombre"))
print("\nFiltrar filas donde la edad es mayor de 30:")
print(df_polars.filter(pl.col("edad") > 30))

DataFrame con Pandas:
  nombre  edad     ciudad
0    Ana    23     Madrid
1   Luis    45  Barcelona
2  María    34   Valencia
3   Juan    25    Sevilla

Seleccionar la columna 'nombre':
0      Ana
1     Luis
2    María
3     Juan
Name: nombre, dtype: object

Filtrar filas donde la edad es mayor de 30:
  nombre  edad     ciudad
1   Luis    45  Barcelona
2  María    34   Valencia

DataFrame con Polars:
shape: (4, 3)
┌────────┬──────┬───────────┐
│ nombre ┆ edad ┆ ciudad    │
│ ---    ┆ ---  ┆ ---       │
│ str    ┆ i64  ┆ str       │
╞════════╪══════╪═══════════╡
│ Ana    ┆ 23   ┆ Madrid    │
│ Luis   ┆ 45   ┆ Barcelona │
│ María  ┆ 34   ┆ Valencia  │
│ Juan   ┆ 25   ┆ Sevilla   │
└────────┴──────┴───────────┘

Seleccionar la columna 'nombre':
shape: (4, 1)
┌────────┐
│ nombre │
│ ---    │
│ str    │
╞════════╡
│ Ana    │
│ Luis   │
│ María  │
│ Juan   │
└────────┘

Filtrar filas donde la edad es mayor de 30:
shape: (2, 3)
┌────────┬──────┬───────────┐
│ nombre ┆ edad ┆ ciudad    │
│ ---    ┆ ---  ┆ ---       │
│ str    ┆ i64  ┆ str       │
╞════════╪══════╪═══════════╡
│ Luis   ┆ 45   ┆ Barcelona │
│ María  ┆ 34   ┆ Valencia  │
└────────┴──────┴───────────┘